version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: front-end:latest

    ports:
      - '5173:5173'
    command: ["yarn", "run", "dev", "--host", "0.0.0.0"]
