const express = require('express');
const app = express();
const port = 3000;
const cors = require('cors');
const dados = {
  "Transporte": [
    {
        "id": 1,
        "rota": "101A",
        "descrição": "Rota expressa da Zona Norte para o Centro",
        "placa": "ABC-1234",
        "assento": 40,
        "transportadora": "Transporte Rápido",
        "localPartida": "Terminal Rodoviário Norte",
        "destino": "Terminal Rodoviário Central",
        "saida": "08:00",
        "chegada": "09:30",
        "nome": "Expresso Rápido",
        "endereço": "Av. Principal, 123",
        "telefone": "+55 11 1234-5678",
        "email": "expresso@transporterapido.com",
        "sitio": "www.transporterapido.com"
    },
    {
        "id": 2,
        "rota": "202B",
        "descrição": "Rota local com paradas",
        "placa": "DEF-5678",
        "assento": 30,
        "transportadora": "Via Local Transportes",
        "localPartida": "Praça da Cidade",
        "destino": "Shopping Center",
        "saida": "09:30",
        "chegada": "10:45",
        "nome": "Circuito da Cidade",
        "endereço": "Rua Principal, 456",
        "telefone": "+55 11 9876-5432",
        "email": "circuito@vialocal.com",
        "sitio": "www.vialocaltransportes.com"
    },
    {
        "id": 3,
        "rota": "303C",
        "descrição": "Rota Interbairros",
        "placa": "GHI-9012",
        "assento": 35,
        "transportadora": "Bairros Conectados",
        "localPartida": "Ponto Central",
        "destino": "Bairro Residencial",
        "saida": "10:00",
        "chegada": "11:15",
        "nome": "Bairros em Conexão",
        "endereço": "Avenida dos Bairros, 789",
        "telefone": "+55 11 7654-3210",
        "email": "bairros@conectados.com",
        "sitio": "www.bairrosconectados.com"
    },
    {
        "id": 4,
        "rota": "404D",
        "descrição": "Rota Turística pela Cidade",
        "placa": "JKL-3456",
        "assento": 25,
        "transportadora": "Turismo Ônibus",
        "localPartida": "Praça Principal",
        "destino": "Mirante Panorâmico",
        "saida": "11:00",
        "chegada": "13:00",
        "nome": "City Tour",
        "endereço": "Rua do Turismo, 101",
        "telefone": "+55 11 2345-6789",
        "email": "turismo@onibus.com",
        "sitio": "www.turismoonibus.com"
    },
    {
        "id": 5,
        "rota": "505E",
        "descrição": "Rota Noturna para Entretenimento",
        "placa": "MNO-7890",
        "assento": 20,
        "transportadora": "Noite Viva Transportes",
        "localPartida": "Rua das Baladas",
        "destino": "Centro de Entretenimento",
        "saida": "21:00",
        "chegada": "23:30",
        "nome": "Rota da Noite",
        "endereço": "Av. da Diversão, 555",
        "telefone": "+55 11 8765-4321",
        "email": "noiteviva@transportes.com",
        "sitio": "www.noitevivatransportes.com"
    },
    {
      "id": 6,
      "rota": "606F",
      "descrição": "Rota Bairro A - Bairro B",
      "placa": "PQR-1234",
      "assento": 30,
      "transportadora": "Bairros Unidos",
      "localPartida": "Praça do Bairro A",
      "destino": "Praça do Bairro B",
      "saida": "07:30",
      "chegada": "08:15",
      "nome": "Conexão de Bairros",
      "endereço": "Avenida dos Moradores, 321",
      "telefone": "+55 44 9876-5432",
      "email": "bairros@unidos.com",
      "sitio": "www.bairrosunidos.com"
    },
    {
      "id": 7,
      "rota": "707G",
      "descrição": "Rota Umuarama - Periferia",
      "placa": "STU-5678",
      "assento": 25,
      "transportadora": "Umuarama Transportes",
      "localPartida": "Terminal Rodoviário Umuarama",
      "destino": "Praça da Periferia",
      "saida": "09:00",
      "chegada": "09:45",
      "nome": "Umuarama Expresso",
      "endereço": "Rua Central, 789",
      "telefone": "+55 44 7654-3210",
      "email": "umuarama@transportes.com",
      "sitio": "www.umuaramatransportes.com"
    },
    {
      "id": 8,
      "rota": "808H",
      "descrição": "Rota Circular do Centro",
      "placa": "VWX-9012",
      "assento": 35,
      "transportadora": "Centro Circular",
      "localPartida": "Praça Central",
      "destino": "Rua Comercial",
      "saida": "11:30",
      "chegada": "12:15",
      "nome": "Circular do Centro",
      "endereço": "Avenida Principal, 456",
      "telefone": "+55 44 2345-6789",
      "email": "centro@circulares.com",
      "sitio": "www.circulardocentro.com"
    }, {
      "id": 9,
      "rota": "909I",
      "descrição": "Rota Parque dos Pássaros - Jardim das Flores",
      "placa": "YZA-3456",
      "assento": 30,
      "transportadora": "Floribus",
      "localPartida": "Praça do Parque dos Pássaros",
      "destino": "Praça do Jardim das Flores",
      "saida": "08:45",
      "chegada": "09:30",
      "nome": "Pássaros para Flores",
      "endereço": "Avenida das Plantas, 789",
      "telefone": "+55 44 8765-4321",
      "email": "floribus@transportes.com",
      "sitio": "www.floribus.com"
    },
    {
      "id": 10,
      "rota": "1010J",
      "descrição": "Rota Vila São Jorge - Conjunto Habitacional",
      "placa": "ABC-6789",
      "assento": 25,
      "transportadora": "Vila Express",
      "localPartida": "Praça da Vila São Jorge",
      "destino": "Praça do Conjunto Habitacional",
      "saida": "10:15",
      "chegada": "11:00",
      "nome": "Expresso da Vila",
      "endereço": "Rua da Comunidade, 456",
      "telefone": "+55 44 9876-5432",
      "email": "vilaexpress@transportes.com",
      "sitio": "www.vilaexpress.com"
    },
    {
      "id": 11,
      "rota": "1111K",
      "descrição": "Rota Universidade - Terminal Rodoviário",
      "placa": "DEF-1234",
      "assento": 35,
      "transportadora": "UniBus",
      "localPartida": "Ponto da Universidade",
      "destino": "Terminal Rodoviário",
      "saida": "11:45",
      "chegada": "12:30",
      "nome": "Conexão Universitária",
      "endereço": "Avenida Acadêmica, 789",
      "telefone": "+55 44 7654-3210",
      "email": "unibus@transportes.com",
      "sitio": "www.unibus.com"
    },
    {
      "id": 12,
      "rota": "1212L",
      "descrição": "Rota Jardim Botânico - Praça da Cidade",
      "placa": "GHI-5678",
      "assento": 40,
      "transportadora": "Botânico Express",
      "localPartida": "Entrada do Jardim Botânico",
      "destino": "Praça Principal",
      "saida": "13:00",
      "chegada": "14:15",
      "nome": "Expresso Botânico",
      "endereço": "Avenida das Plantas, 123",
      "telefone": "+55 44 2345-6789",
      "email": "botanicoexpress@transportes.com",
      "sitio": "www.botanicoexpress.com"
    },
    {
      "id": 13,
      "rota": "1313M",
      "descrição": "Rota Distrito Industrial - Centro Comercial",
      "placa": "JKL-9012",
      "assento": 30,
      "transportadora": "Distrito Rápido",
      "localPartida": "Ponto do Distrito Industrial",
      "destino": "Centro Comercial",
      "saida": "14:30",
      "chegada": "15:15",
      "nome": "Rápido Industrial",
      "endereço": "Rua Industrial, 456",
      "telefone": "+55 44 8765-4321",
      "email": "distritorapido@transportes.com",
      "sitio": "www.distritorapido.com"
    },
    {
      "id": 14,
      "rota": "1414N",
      "descrição": "Rota Jardim Panorâmico - Bairro Residencial",
      "placa": "MNO-2345",
      "assento": 35,
      "transportadora": "Panorama Transportes",
      "localPartida": "Praça do Jardim Panorâmico",
      "destino": "Praça do Bairro Residencial",
      "saida": "15:30",
      "chegada": "16:15",
      "nome": "Panorâmico Residencial",
      "endereço": "Avenida Vista Panorâmica, 789",
      "telefone": "+55 44 9876-5432",
      "email": "panorama@transportes.com",
      "sitio": "www.panoramatransportes.com"
    },
    {
      "id": 15,
      "rota": "1515O",
      "descrição": "Rota Parque Aquático - Praça Central",
      "placa": "PQR-3456",
      "assento": 25,
      "transportadora": "AquaBus",
      "localPartida": "Entrada do Parque Aquático",
      "destino": "Praça Central",
      "saida": "16:45",
      "chegada": "17:30",
      "nome": "AquaExpress",
      "endereço": "Rua da Diversão, 123",
      "telefone": "+55 44 7654-3210",
      "email": "aquabus@transportes.com",
      "sitio": "www.aquabus.com"
    },
    {
      "id": 16,
      "rota": "1616P",
      "descrição": "Rota Hospital Municipal - Residencial dos Médicos",
      "placa": "STU-5678",
      "assento": 40,
      "transportadora": "Médico Express",
      "localPartida": "Entrada do Hospital Municipal",
      "destino": "Praça do Residencial dos Médicos",
      "saida": "18:00",
      "chegada": "19:00",
      "nome": "Expresso Médico",
      "endereço": "Avenida dos Doutores, 456",
      "telefone": "+55 44 2345-6789",
      "email": "medicoexpress@transportes.com",
      "sitio": "www.medicoexpress.com"
    },
    {
      "id": 17,
      "rota": "1717Q",
      "descrição": "Rota Escola Municipal - Parque Infantil",
      "placa": "VWX-9012",
      "assento": 35,
      "transportadora": "Educação Transportes",
      "localPartida": "Portão da Escola Municipal",
      "destino": "Praça do Parque Infantil",
      "saida": "19:15",
      "chegada": "20:00",
      "nome": "Educação em Movimento",
      "endereço": "Rua da Educação, 789",
      "telefone": "+55 44 8765-4321",
      "email": "educacao@transportes.com",
      "sitio": "www.educacaotransportes.com"
    },
    {
      "id": 18,
      "rota": "1818R",
      "descrição": "Rota Shopping Center - Cinemas da Cidade",
      "placa": "YZA-1234",
      "assento": 30,
      "transportadora": "City Shopping Bus",
      "localPartida": "Entrada do Shopping Center",
      "destino": "Praça dos Cinemas",
      "saida": "20:30",
      "chegada": "21:15",
      "nome": "Shopping Express",
      "endereço": "Avenida das Lojas, 456",
      "telefone": "+55 44 9876-5432",
      "email": "cityshopping@transportes.com",
      "sitio": "www.cityshoppingbus.com"
    },
    {
      "id": 19,
      "rota": "1919S",
      "descrição": "Rota Parque Ecológico - Bosque Municipal",
      "placa": "ABC-6789",
      "assento": 25,
      "transportadora": "EcoBus",
      "localPartida": "Entrada do Parque Ecológico",
      "destino": "Praça do Bosque",
      "saida": "21:45",
      "chegada": "22:30",
      "nome": "EcoTour",
      "endereço": "Avenida da Natureza, 789",
      "telefone": "+55 44 7654-3210",
      "email": "ecobus@transportes.com",
      "sitio": "www.ecobus.com"
    }
],
"Usuario": [
  {
    "id": 4,
    "nome": "Matheus",
    "cpf": "0000000",
    "endereço": "estrada cascalho",
    "email": "matheus@gmail.com",
    "telefone": 9999999,
    "login": "matheus",
    "password": "matheus"
  }]


};
app.use(cors());
app.get('/Transporte', (req, res) => {
  res.json(dados.Transporte);
});
app.get('/Usuario', (req, res) => {
  res.json(dados.Usuario);
});
app.listen(port, () => {
  console.log(`Servidor está rodando em http://localhost:${port}`);
});
